[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.11,<4"
pandoc = ">=3.9,<4"
pre-commit = ">=4,<5"
nodejs = ">=20,<21"

[tasks]
gen-grammars = "python tools/gen-grammars.py"
check-grammars = "python tools/gen-grammars.py --check"
test-kate = "bash kate/test/check.sh"
npm-install       = { cmd = "npm install", cwd = "tree-sitter" }
gen-tree-sitter   = { cmd = "npx tree-sitter generate", cwd = "tree-sitter", depends-on = ["npm-install"] }
test-tree-sitter  = { cmd = "npx tree-sitter test", cwd = "tree-sitter", depends-on = ["gen-tree-sitter"] }
check-tree-sitter = { cmd = "npx tree-sitter test", cwd = "tree-sitter", depends-on = ["gen-tree-sitter"] }
check             = { depends-on = ["check-grammars", "test-kate", "check-tree-sitter"] }
