#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 37
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  sym_integer = 3,
  sym_float = 4,
  anon_sym_DQUOTE = 5,
  aux_sym_string_token1 = 6,
  sym_escape_sequence = 7,
  sym_invalid_escape = 8,
  sym_boolean = 9,
  anon_sym_COMMA = 10,
  sym_line_comment = 11,
  sym_doc_line = 12,
  sym__newline = 13,
  sym_block_comment = 14,
  sym_doc_block = 15,
  sym__lparen = 16,
  sym__rparen = 17,
  sym__lbracket = 18,
  sym__rbracket = 19,
  sym_module = 20,
  aux_sym__sep = 21,
  sym__statement = 22,
  sym__expression = 23,
  sym__literal = 24,
  sym_string = 25,
  sym_array_literal = 26,
  sym_tuple_literal = 27,
  aux_sym_module_repeat1 = 28,
  aux_sym_string_repeat1 = 29,
  aux_sym_array_literal_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_invalid_escape] = "invalid_escape",
  [sym_boolean] = "boolean",
  [anon_sym_COMMA] = ",",
  [sym_line_comment] = "line_comment",
  [sym_doc_line] = "doc_line",
  [sym__newline] = "_newline",
  [sym_block_comment] = "block_comment",
  [sym_doc_block] = "doc_block",
  [sym__lparen] = "_lparen",
  [sym__rparen] = "_rparen",
  [sym__lbracket] = "_lbracket",
  [sym__rbracket] = "_rbracket",
  [sym_module] = "module",
  [aux_sym__sep] = "_sep",
  [sym__statement] = "_statement",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym_string] = "string",
  [sym_array_literal] = "array_literal",
  [sym_tuple_literal] = "tuple_literal",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_invalid_escape] = sym_invalid_escape,
  [sym_boolean] = sym_boolean,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_line_comment] = sym_line_comment,
  [sym_doc_line] = sym_doc_line,
  [sym__newline] = sym__newline,
  [sym_block_comment] = sym_block_comment,
  [sym_doc_block] = sym_doc_block,
  [sym__lparen] = sym__lparen,
  [sym__rparen] = sym__rparen,
  [sym__lbracket] = sym__lbracket,
  [sym__rbracket] = sym__rbracket,
  [sym_module] = sym_module,
  [aux_sym__sep] = aux_sym__sep,
  [sym__statement] = sym__statement,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym_string] = sym_string,
  [sym_array_literal] = sym_array_literal,
  [sym_tuple_literal] = sym_tuple_literal,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_invalid_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_line] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_block] = {
    .visible = true,
    .named = true,
  },
  [sym__lparen] = {
    .visible = false,
    .named = true,
  },
  [sym__rparen] = {
    .visible = false,
    .named = true,
  },
  [sym__lbracket] = {
    .visible = false,
    .named = true,
  },
  [sym__rbracket] = {
    .visible = false,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__sep] = {
    .visible = false,
    .named = false,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 11,
  [13] = 8,
  [14] = 7,
  [15] = 15,
  [16] = 15,
  [17] = 11,
  [18] = 7,
  [19] = 9,
  [20] = 8,
  [21] = 15,
  [22] = 11,
  [23] = 7,
  [24] = 9,
  [25] = 8,
  [26] = 15,
  [27] = 27,
  [28] = 28,
  [29] = 27,
  [30] = 30,
  [31] = 30,
  [32] = 30,
  [33] = 30,
  [34] = 28,
  [35] = 28,
  [36] = 28,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 40,
  [44] = 41,
  [45] = 45,
  [46] = 46,
  [47] = 40,
  [48] = 41,
  [49] = 41,
  [50] = 40,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 52,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 55,
  [63] = 55,
  [64] = 52,
  [65] = 58,
  [66] = 66,
  [67] = 61,
  [68] = 58,
  [69] = 69,
  [70] = 70,
  [71] = 55,
  [72] = 52,
  [73] = 58,
  [74] = 74,
  [75] = 70,
  [76] = 61,
  [77] = 77,
  [78] = 61,
  [79] = 79,
  [80] = 74,
  [81] = 59,
  [82] = 74,
  [83] = 56,
  [84] = 79,
  [85] = 69,
  [86] = 77,
  [87] = 87,
  [88] = 53,
  [89] = 60,
  [90] = 54,
  [91] = 56,
  [92] = 87,
  [93] = 79,
  [94] = 69,
  [95] = 77,
  [96] = 53,
  [97] = 60,
  [98] = 59,
  [99] = 54,
  [100] = 100,
  [101] = 74,
  [102] = 79,
  [103] = 77,
  [104] = 53,
  [105] = 60,
  [106] = 69,
  [107] = 54,
  [108] = 100,
  [109] = 56,
  [110] = 100,
  [111] = 59,
  [112] = 100,
  [113] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 16,
        '#', 25,
        '%', 26,
        ',', 23,
        '.', 5,
        '0', 10,
        ';', 9,
        '\\', 3,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '%') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(2);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(5);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '%') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n' ||
          lookahead == ';') ADVANCE(20);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(25);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n' ||
          lookahead == ';') ADVANCE(20);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(26);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_invalid_escape);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_doc_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 't') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 4},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 4},
  [16] = {.lex_state = 0, .external_lex_state = 4},
  [17] = {.lex_state = 0, .external_lex_state = 3},
  [18] = {.lex_state = 0, .external_lex_state = 3},
  [19] = {.lex_state = 0, .external_lex_state = 3},
  [20] = {.lex_state = 0, .external_lex_state = 4},
  [21] = {.lex_state = 0, .external_lex_state = 4},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 4},
  [26] = {.lex_state = 0, .external_lex_state = 4},
  [27] = {.lex_state = 0, .external_lex_state = 5},
  [28] = {.lex_state = 0, .external_lex_state = 5},
  [29] = {.lex_state = 0, .external_lex_state = 5},
  [30] = {.lex_state = 0, .external_lex_state = 5},
  [31] = {.lex_state = 0, .external_lex_state = 5},
  [32] = {.lex_state = 0, .external_lex_state = 5},
  [33] = {.lex_state = 0, .external_lex_state = 5},
  [34] = {.lex_state = 0, .external_lex_state = 5},
  [35] = {.lex_state = 0, .external_lex_state = 5},
  [36] = {.lex_state = 0, .external_lex_state = 5},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 6},
  [39] = {.lex_state = 0, .external_lex_state = 6},
  [40] = {.lex_state = 1, .external_lex_state = 7},
  [41] = {.lex_state = 1, .external_lex_state = 7},
  [42] = {.lex_state = 1, .external_lex_state = 7},
  [43] = {.lex_state = 1, .external_lex_state = 7},
  [44] = {.lex_state = 1, .external_lex_state = 7},
  [45] = {.lex_state = 0, .external_lex_state = 6},
  [46] = {.lex_state = 0, .external_lex_state = 6},
  [47] = {.lex_state = 1, .external_lex_state = 7},
  [48] = {.lex_state = 1, .external_lex_state = 7},
  [49] = {.lex_state = 1, .external_lex_state = 7},
  [50] = {.lex_state = 1, .external_lex_state = 7},
  [51] = {.lex_state = 0, .external_lex_state = 6},
  [52] = {.lex_state = 0, .external_lex_state = 8},
  [53] = {.lex_state = 0, .external_lex_state = 6},
  [54] = {.lex_state = 0, .external_lex_state = 6},
  [55] = {.lex_state = 0, .external_lex_state = 8},
  [56] = {.lex_state = 0, .external_lex_state = 6},
  [57] = {.lex_state = 0, .external_lex_state = 8},
  [58] = {.lex_state = 0, .external_lex_state = 9},
  [59] = {.lex_state = 0, .external_lex_state = 6},
  [60] = {.lex_state = 0, .external_lex_state = 6},
  [61] = {.lex_state = 0, .external_lex_state = 9},
  [62] = {.lex_state = 0, .external_lex_state = 8},
  [63] = {.lex_state = 0, .external_lex_state = 8},
  [64] = {.lex_state = 0, .external_lex_state = 8},
  [65] = {.lex_state = 0, .external_lex_state = 9},
  [66] = {.lex_state = 0, .external_lex_state = 6},
  [67] = {.lex_state = 0, .external_lex_state = 9},
  [68] = {.lex_state = 0, .external_lex_state = 9},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 9},
  [71] = {.lex_state = 0, .external_lex_state = 8},
  [72] = {.lex_state = 0, .external_lex_state = 8},
  [73] = {.lex_state = 0, .external_lex_state = 9},
  [74] = {.lex_state = 0, .external_lex_state = 6},
  [75] = {.lex_state = 0, .external_lex_state = 8},
  [76] = {.lex_state = 0, .external_lex_state = 9},
  [77] = {.lex_state = 0, .external_lex_state = 6},
  [78] = {.lex_state = 0, .external_lex_state = 9},
  [79] = {.lex_state = 0, .external_lex_state = 6},
  [80] = {.lex_state = 0, .external_lex_state = 8},
  [81] = {.lex_state = 0, .external_lex_state = 9},
  [82] = {.lex_state = 0, .external_lex_state = 9},
  [83] = {.lex_state = 0, .external_lex_state = 9},
  [84] = {.lex_state = 0, .external_lex_state = 9},
  [85] = {.lex_state = 0, .external_lex_state = 9},
  [86] = {.lex_state = 0, .external_lex_state = 9},
  [87] = {.lex_state = 0, .external_lex_state = 9},
  [88] = {.lex_state = 0, .external_lex_state = 9},
  [89] = {.lex_state = 0, .external_lex_state = 9},
  [90] = {.lex_state = 0, .external_lex_state = 9},
  [91] = {.lex_state = 0, .external_lex_state = 8},
  [92] = {.lex_state = 0, .external_lex_state = 8},
  [93] = {.lex_state = 0, .external_lex_state = 8},
  [94] = {.lex_state = 0, .external_lex_state = 8},
  [95] = {.lex_state = 0, .external_lex_state = 8},
  [96] = {.lex_state = 0, .external_lex_state = 8},
  [97] = {.lex_state = 0, .external_lex_state = 8},
  [98] = {.lex_state = 0, .external_lex_state = 8},
  [99] = {.lex_state = 0, .external_lex_state = 8},
  [100] = {.lex_state = 0, .external_lex_state = 7},
  [101] = {.lex_state = 0, .external_lex_state = 7},
  [102] = {.lex_state = 0, .external_lex_state = 7},
  [103] = {.lex_state = 0, .external_lex_state = 7},
  [104] = {.lex_state = 0, .external_lex_state = 7},
  [105] = {.lex_state = 0, .external_lex_state = 7},
  [106] = {.lex_state = 0, .external_lex_state = 7},
  [107] = {.lex_state = 0, .external_lex_state = 7},
  [108] = {.lex_state = 0, .external_lex_state = 7},
  [109] = {.lex_state = 0, .external_lex_state = 7},
  [110] = {.lex_state = 0, .external_lex_state = 7},
  [111] = {.lex_state = 0, .external_lex_state = 7},
  [112] = {.lex_state = 0, .external_lex_state = 7},
  [113] = {.lex_state = 0, .external_lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_invalid_escape] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(1),
    [sym__rparen] = ACTIONS(1),
    [sym__lbracket] = ACTIONS(1),
    [sym__rbracket] = ACTIONS(1),
  },
  [1] = {
    [sym_module] = STATE(113),
    [aux_sym__sep] = STATE(2),
    [sym__statement] = STATE(38),
    [sym__expression] = STATE(38),
    [sym__literal] = STATE(38),
    [sym_string] = STATE(38),
    [sym_array_literal] = STATE(38),
    [sym_tuple_literal] = STATE(38),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(9),
    [sym_integer] = ACTIONS(7),
    [sym_float] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym__newline] = ACTIONS(9),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(15),
    [sym__lbracket] = ACTIONS(17),
  },
  [2] = {
    [aux_sym__sep] = STATE(37),
    [sym__statement] = STATE(51),
    [sym__expression] = STATE(51),
    [sym__literal] = STATE(51),
    [sym_string] = STATE(51),
    [sym_array_literal] = STATE(51),
    [sym_tuple_literal] = STATE(51),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(23),
    [sym_integer] = ACTIONS(21),
    [sym_float] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(21),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym__newline] = ACTIONS(23),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(15),
    [sym__lbracket] = ACTIONS(17),
  },
  [3] = {
    [aux_sym__sep] = STATE(37),
    [sym__statement] = STATE(66),
    [sym__expression] = STATE(66),
    [sym__literal] = STATE(66),
    [sym_string] = STATE(66),
    [sym_array_literal] = STATE(66),
    [sym_tuple_literal] = STATE(66),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(23),
    [sym_integer] = ACTIONS(29),
    [sym_float] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(29),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym__newline] = ACTIONS(23),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(15),
    [sym__lbracket] = ACTIONS(17),
  },
  [4] = {
    [aux_sym__sep] = STATE(37),
    [sym__statement] = STATE(66),
    [sym__expression] = STATE(66),
    [sym__literal] = STATE(66),
    [sym_string] = STATE(66),
    [sym_array_literal] = STATE(66),
    [sym_tuple_literal] = STATE(66),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(23),
    [sym_integer] = ACTIONS(29),
    [sym_float] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(29),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym__newline] = ACTIONS(23),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(15),
    [sym__lbracket] = ACTIONS(17),
  },
  [5] = {
    [aux_sym__sep] = STATE(37),
    [sym__statement] = STATE(66),
    [sym__expression] = STATE(66),
    [sym__literal] = STATE(66),
    [sym_string] = STATE(66),
    [sym_array_literal] = STATE(66),
    [sym_tuple_literal] = STATE(66),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(23),
    [sym_integer] = ACTIONS(29),
    [sym_float] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(29),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym__newline] = ACTIONS(23),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(15),
    [sym__lbracket] = ACTIONS(17),
  },
  [6] = {
    [aux_sym__sep] = STATE(37),
    [sym__statement] = STATE(66),
    [sym__expression] = STATE(66),
    [sym__literal] = STATE(66),
    [sym_string] = STATE(66),
    [sym_array_literal] = STATE(66),
    [sym_tuple_literal] = STATE(66),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(23),
    [sym_integer] = ACTIONS(29),
    [sym_float] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(29),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym__newline] = ACTIONS(23),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(15),
    [sym__lbracket] = ACTIONS(17),
  },
  [7] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(47),
  },
  [8] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__rparen] = ACTIONS(57),
    [sym__lbracket] = ACTIONS(59),
  },
  [9] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(61),
  },
  [10] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(63),
  },
  [11] = {
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(62),
    [sym_string] = STATE(62),
    [sym_array_literal] = STATE(62),
    [sym_tuple_literal] = STATE(62),
    [sym_identifier] = ACTIONS(65),
    [sym_integer] = ACTIONS(65),
    [sym_float] = ACTIONS(67),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(65),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(69),
  },
  [12] = {
    [sym__expression] = STATE(55),
    [sym__literal] = STATE(55),
    [sym_string] = STATE(55),
    [sym_array_literal] = STATE(55),
    [sym_tuple_literal] = STATE(55),
    [sym_identifier] = ACTIONS(71),
    [sym_integer] = ACTIONS(71),
    [sym_float] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(71),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(75),
  },
  [13] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__rparen] = ACTIONS(77),
    [sym__lbracket] = ACTIONS(59),
  },
  [14] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(79),
  },
  [15] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__rparen] = ACTIONS(81),
    [sym__lbracket] = ACTIONS(59),
  },
  [16] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__rparen] = ACTIONS(83),
    [sym__lbracket] = ACTIONS(59),
  },
  [17] = {
    [sym__expression] = STATE(63),
    [sym__literal] = STATE(63),
    [sym_string] = STATE(63),
    [sym_array_literal] = STATE(63),
    [sym_tuple_literal] = STATE(63),
    [sym_identifier] = ACTIONS(85),
    [sym_integer] = ACTIONS(85),
    [sym_float] = ACTIONS(87),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(85),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(89),
  },
  [18] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(91),
  },
  [19] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(93),
  },
  [20] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__rparen] = ACTIONS(95),
    [sym__lbracket] = ACTIONS(59),
  },
  [21] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__rparen] = ACTIONS(97),
    [sym__lbracket] = ACTIONS(59),
  },
  [22] = {
    [sym__expression] = STATE(71),
    [sym__literal] = STATE(71),
    [sym_string] = STATE(71),
    [sym_array_literal] = STATE(71),
    [sym_tuple_literal] = STATE(71),
    [sym_identifier] = ACTIONS(99),
    [sym_integer] = ACTIONS(99),
    [sym_float] = ACTIONS(101),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(99),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(103),
  },
  [23] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(105),
  },
  [24] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
    [sym__rbracket] = ACTIONS(107),
  },
  [25] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__rparen] = ACTIONS(109),
    [sym__lbracket] = ACTIONS(59),
  },
  [26] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__rparen] = ACTIONS(111),
    [sym__lbracket] = ACTIONS(59),
  },
  [27] = {
    [sym__expression] = STATE(92),
    [sym__literal] = STATE(92),
    [sym_string] = STATE(92),
    [sym_array_literal] = STATE(92),
    [sym_tuple_literal] = STATE(92),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [sym_float] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_boolean] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(43),
    [sym__lbracket] = ACTIONS(45),
  },
  [28] = {
    [sym__expression] = STATE(112),
    [sym__literal] = STATE(112),
    [sym_string] = STATE(112),
    [sym_array_literal] = STATE(112),
    [sym_tuple_literal] = STATE(112),
    [sym_identifier] = ACTIONS(113),
    [sym_integer] = ACTIONS(113),
    [sym_float] = ACTIONS(115),
    [anon_sym_DQUOTE] = ACTIONS(117),
    [sym_boolean] = ACTIONS(113),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(119),
    [sym__lbracket] = ACTIONS(121),
  },
  [29] = {
    [sym__expression] = STATE(87),
    [sym__literal] = STATE(87),
    [sym_string] = STATE(87),
    [sym_array_literal] = STATE(87),
    [sym_tuple_literal] = STATE(87),
    [sym_identifier] = ACTIONS(49),
    [sym_integer] = ACTIONS(49),
    [sym_float] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__lbracket] = ACTIONS(59),
  },
  [30] = {
    [sym__expression] = STATE(68),
    [sym__literal] = STATE(68),
    [sym_string] = STATE(68),
    [sym_array_literal] = STATE(68),
    [sym_tuple_literal] = STATE(68),
    [sym_identifier] = ACTIONS(123),
    [sym_integer] = ACTIONS(123),
    [sym_float] = ACTIONS(125),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(123),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__lbracket] = ACTIONS(59),
  },
  [31] = {
    [sym__expression] = STATE(58),
    [sym__literal] = STATE(58),
    [sym_string] = STATE(58),
    [sym_array_literal] = STATE(58),
    [sym_tuple_literal] = STATE(58),
    [sym_identifier] = ACTIONS(127),
    [sym_integer] = ACTIONS(127),
    [sym_float] = ACTIONS(129),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(127),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__lbracket] = ACTIONS(59),
  },
  [32] = {
    [sym__expression] = STATE(65),
    [sym__literal] = STATE(65),
    [sym_string] = STATE(65),
    [sym_array_literal] = STATE(65),
    [sym_tuple_literal] = STATE(65),
    [sym_identifier] = ACTIONS(131),
    [sym_integer] = ACTIONS(131),
    [sym_float] = ACTIONS(133),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(131),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__lbracket] = ACTIONS(59),
  },
  [33] = {
    [sym__expression] = STATE(73),
    [sym__literal] = STATE(73),
    [sym_string] = STATE(73),
    [sym_array_literal] = STATE(73),
    [sym_tuple_literal] = STATE(73),
    [sym_identifier] = ACTIONS(135),
    [sym_integer] = ACTIONS(135),
    [sym_float] = ACTIONS(137),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [sym_boolean] = ACTIONS(135),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(55),
    [sym__lbracket] = ACTIONS(59),
  },
  [34] = {
    [sym__expression] = STATE(108),
    [sym__literal] = STATE(108),
    [sym_string] = STATE(108),
    [sym_array_literal] = STATE(108),
    [sym_tuple_literal] = STATE(108),
    [sym_identifier] = ACTIONS(139),
    [sym_integer] = ACTIONS(139),
    [sym_float] = ACTIONS(141),
    [anon_sym_DQUOTE] = ACTIONS(117),
    [sym_boolean] = ACTIONS(139),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(119),
    [sym__lbracket] = ACTIONS(121),
  },
  [35] = {
    [sym__expression] = STATE(100),
    [sym__literal] = STATE(100),
    [sym_string] = STATE(100),
    [sym_array_literal] = STATE(100),
    [sym_tuple_literal] = STATE(100),
    [sym_identifier] = ACTIONS(143),
    [sym_integer] = ACTIONS(143),
    [sym_float] = ACTIONS(145),
    [anon_sym_DQUOTE] = ACTIONS(117),
    [sym_boolean] = ACTIONS(143),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(119),
    [sym__lbracket] = ACTIONS(121),
  },
  [36] = {
    [sym__expression] = STATE(110),
    [sym__literal] = STATE(110),
    [sym_string] = STATE(110),
    [sym_array_literal] = STATE(110),
    [sym_tuple_literal] = STATE(110),
    [sym_identifier] = ACTIONS(147),
    [sym_integer] = ACTIONS(147),
    [sym_float] = ACTIONS(149),
    [anon_sym_DQUOTE] = ACTIONS(117),
    [sym_boolean] = ACTIONS(147),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_line] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_doc_block] = ACTIONS(3),
    [sym__lparen] = ACTIONS(119),
    [sym__lbracket] = ACTIONS(121),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    STATE(37), 1,
      aux_sym__sep,
    ACTIONS(155), 2,
      sym__newline,
      anon_sym_SEMI,
    ACTIONS(153), 3,
      sym_integer,
      sym_boolean,
      sym_identifier,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(151), 5,
      sym__lparen,
      sym__lbracket,
      ts_builtin_sym_end,
      sym_float,
      anon_sym_DQUOTE,
  [26] = 5,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym__sep,
    STATE(39), 1,
      aux_sym_module_repeat1,
    ACTIONS(158), 2,
      sym__newline,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [46] = 5,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym__sep,
    STATE(46), 1,
      aux_sym_module_repeat1,
    ACTIONS(160), 2,
      sym__newline,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [66] = 5,
    ACTIONS(162), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(164), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [86] = 5,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(170), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [106] = 5,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(174), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [126] = 5,
    ACTIONS(177), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(179), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [146] = 5,
    ACTIONS(181), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(170), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [166] = 5,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym__sep,
    STATE(46), 1,
      aux_sym_module_repeat1,
    ACTIONS(183), 2,
      sym__newline,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [186] = 5,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym__sep,
    STATE(46), 1,
      aux_sym_module_repeat1,
    ACTIONS(187), 2,
      sym__newline,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [206] = 5,
    ACTIONS(190), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(192), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [226] = 5,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(170), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [246] = 5,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(170), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [266] = 5,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    STATE(49), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_block_comment,
      sym_doc_block,
    ACTIONS(166), 2,
      sym_line_comment,
      sym_doc_line,
    ACTIONS(200), 3,
      aux_sym_string_token1,
      sym_escape_sequence,
      sym_invalid_escape,
  [286] = 5,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym__sep,
    STATE(45), 1,
      aux_sym_module_repeat1,
    ACTIONS(160), 2,
      sym__newline,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [306] = 4,
    ACTIONS(105), 1,
      sym__rbracket,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [322] = 2,
    ACTIONS(204), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [334] = 2,
    ACTIONS(206), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [346] = 4,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      sym__rbracket,
    STATE(57), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [362] = 2,
    ACTIONS(212), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [374] = 4,
    ACTIONS(79), 1,
      sym__rbracket,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [390] = 4,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      sym__rparen,
    STATE(61), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [406] = 2,
    ACTIONS(220), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [418] = 2,
    ACTIONS(222), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [430] = 4,
    ACTIONS(57), 1,
      sym__rparen,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [446] = 4,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      sym__rbracket,
    STATE(52), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [462] = 4,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      sym__rbracket,
    STATE(64), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [478] = 4,
    ACTIONS(91), 1,
      sym__rbracket,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [494] = 4,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      sym__rparen,
    STATE(67), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [510] = 2,
    ACTIONS(185), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [522] = 4,
    ACTIONS(95), 1,
      sym__rparen,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [538] = 4,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      sym__rparen,
    STATE(78), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [554] = 2,
    ACTIONS(246), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [566] = 4,
    ACTIONS(248), 1,
      anon_sym_COMMA,
    ACTIONS(251), 1,
      sym__rparen,
    STATE(70), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [582] = 4,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      sym__rbracket,
    STATE(72), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [598] = 4,
    ACTIONS(47), 1,
      sym__rbracket,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [614] = 4,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(261), 1,
      sym__rparen,
    STATE(76), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [630] = 2,
    ACTIONS(263), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [642] = 4,
    ACTIONS(251), 1,
      sym__rbracket,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [658] = 4,
    ACTIONS(109), 1,
      sym__rparen,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [674] = 2,
    ACTIONS(270), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [686] = 4,
    ACTIONS(77), 1,
      sym__rparen,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_array_literal_repeat1,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [702] = 2,
    ACTIONS(274), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [714] = 2,
    ACTIONS(263), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [725] = 2,
    ACTIONS(220), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [736] = 2,
    ACTIONS(263), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [747] = 2,
    ACTIONS(212), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [758] = 2,
    ACTIONS(274), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [769] = 2,
    ACTIONS(246), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [780] = 2,
    ACTIONS(270), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [791] = 2,
    ACTIONS(251), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [802] = 2,
    ACTIONS(204), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [813] = 2,
    ACTIONS(222), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [824] = 2,
    ACTIONS(206), 2,
      sym__rparen,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [835] = 2,
    ACTIONS(212), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [846] = 2,
    ACTIONS(251), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [857] = 2,
    ACTIONS(274), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [868] = 2,
    ACTIONS(246), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [879] = 2,
    ACTIONS(270), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [890] = 2,
    ACTIONS(204), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [901] = 2,
    ACTIONS(222), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [912] = 2,
    ACTIONS(220), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [923] = 2,
    ACTIONS(206), 2,
      sym__rbracket,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [934] = 2,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [944] = 2,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [954] = 2,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [964] = 2,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [974] = 2,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [984] = 2,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [994] = 2,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [1004] = 2,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [1014] = 2,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [1024] = 2,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [1034] = 2,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [1044] = 2,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [1054] = 2,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
  [1064] = 2,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 4,
      sym_block_comment,
      sym_doc_block,
      sym_line_comment,
      sym_doc_line,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(37)] = 0,
  [SMALL_STATE(38)] = 26,
  [SMALL_STATE(39)] = 46,
  [SMALL_STATE(40)] = 66,
  [SMALL_STATE(41)] = 86,
  [SMALL_STATE(42)] = 106,
  [SMALL_STATE(43)] = 126,
  [SMALL_STATE(44)] = 146,
  [SMALL_STATE(45)] = 166,
  [SMALL_STATE(46)] = 186,
  [SMALL_STATE(47)] = 206,
  [SMALL_STATE(48)] = 226,
  [SMALL_STATE(49)] = 246,
  [SMALL_STATE(50)] = 266,
  [SMALL_STATE(51)] = 286,
  [SMALL_STATE(52)] = 306,
  [SMALL_STATE(53)] = 322,
  [SMALL_STATE(54)] = 334,
  [SMALL_STATE(55)] = 346,
  [SMALL_STATE(56)] = 362,
  [SMALL_STATE(57)] = 374,
  [SMALL_STATE(58)] = 390,
  [SMALL_STATE(59)] = 406,
  [SMALL_STATE(60)] = 418,
  [SMALL_STATE(61)] = 430,
  [SMALL_STATE(62)] = 446,
  [SMALL_STATE(63)] = 462,
  [SMALL_STATE(64)] = 478,
  [SMALL_STATE(65)] = 494,
  [SMALL_STATE(66)] = 510,
  [SMALL_STATE(67)] = 522,
  [SMALL_STATE(68)] = 538,
  [SMALL_STATE(69)] = 554,
  [SMALL_STATE(70)] = 566,
  [SMALL_STATE(71)] = 582,
  [SMALL_STATE(72)] = 598,
  [SMALL_STATE(73)] = 614,
  [SMALL_STATE(74)] = 630,
  [SMALL_STATE(75)] = 642,
  [SMALL_STATE(76)] = 658,
  [SMALL_STATE(77)] = 674,
  [SMALL_STATE(78)] = 686,
  [SMALL_STATE(79)] = 702,
  [SMALL_STATE(80)] = 714,
  [SMALL_STATE(81)] = 725,
  [SMALL_STATE(82)] = 736,
  [SMALL_STATE(83)] = 747,
  [SMALL_STATE(84)] = 758,
  [SMALL_STATE(85)] = 769,
  [SMALL_STATE(86)] = 780,
  [SMALL_STATE(87)] = 791,
  [SMALL_STATE(88)] = 802,
  [SMALL_STATE(89)] = 813,
  [SMALL_STATE(90)] = 824,
  [SMALL_STATE(91)] = 835,
  [SMALL_STATE(92)] = 846,
  [SMALL_STATE(93)] = 857,
  [SMALL_STATE(94)] = 868,
  [SMALL_STATE(95)] = 879,
  [SMALL_STATE(96)] = 890,
  [SMALL_STATE(97)] = 901,
  [SMALL_STATE(98)] = 912,
  [SMALL_STATE(99)] = 923,
  [SMALL_STATE(100)] = 934,
  [SMALL_STATE(101)] = 944,
  [SMALL_STATE(102)] = 954,
  [SMALL_STATE(103)] = 964,
  [SMALL_STATE(104)] = 974,
  [SMALL_STATE(105)] = 984,
  [SMALL_STATE(106)] = 994,
  [SMALL_STATE(107)] = 1004,
  [SMALL_STATE(108)] = 1014,
  [SMALL_STATE(109)] = 1024,
  [SMALL_STATE(110)] = 1034,
  [SMALL_STATE(111)] = 1044,
  [SMALL_STATE(112)] = 1054,
  [SMALL_STATE(113)] = 1064,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sep, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__sep, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sep, 2, 0, 0), SHIFT_REPEAT(37),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 5, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_literal, 7, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_literal, 6, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 4, 0, 0),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_literal, 5, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [284] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token_block_comment = 1,
  ts_external_token_doc_block = 2,
  ts_external_token__lparen = 3,
  ts_external_token__rparen = 4,
  ts_external_token__lbracket = 5,
  ts_external_token__rbracket = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token_block_comment] = sym_block_comment,
  [ts_external_token_doc_block] = sym_doc_block,
  [ts_external_token__lparen] = sym__lparen,
  [ts_external_token__rparen] = sym__rparen,
  [ts_external_token__lbracket] = sym__lbracket,
  [ts_external_token__rbracket] = sym__rbracket,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
    [ts_external_token__lparen] = true,
    [ts_external_token__rparen] = true,
    [ts_external_token__lbracket] = true,
    [ts_external_token__rbracket] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
    [ts_external_token__lparen] = true,
    [ts_external_token__lbracket] = true,
  },
  [3] = {
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
    [ts_external_token__lparen] = true,
    [ts_external_token__lbracket] = true,
    [ts_external_token__rbracket] = true,
  },
  [4] = {
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
    [ts_external_token__lparen] = true,
    [ts_external_token__rparen] = true,
    [ts_external_token__lbracket] = true,
  },
  [5] = {
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
    [ts_external_token__lparen] = true,
    [ts_external_token__lbracket] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
  },
  [7] = {
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
  },
  [8] = {
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
    [ts_external_token__rbracket] = true,
  },
  [9] = {
    [ts_external_token_block_comment] = true,
    [ts_external_token_doc_block] = true,
    [ts_external_token__rparen] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_flatppl_external_scanner_create(void);
void tree_sitter_flatppl_external_scanner_destroy(void *);
bool tree_sitter_flatppl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_flatppl_external_scanner_serialize(void *, char *);
void tree_sitter_flatppl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_flatppl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_flatppl_external_scanner_create,
      tree_sitter_flatppl_external_scanner_destroy,
      tree_sitter_flatppl_external_scanner_scan,
      tree_sitter_flatppl_external_scanner_serialize,
      tree_sitter_flatppl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
